name: "Streaming Camera Tag Detection"
description: "Detects QR codes in an IP camera stream and sends tag events to Home Assistant"
version: "0.0.1"
slug: "ha_cam_tag"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  tag_event_device_id: "00000000000000000000000000000000"
  camera_rtsp_stream: "rtsp://camera-ip-address/"
schema:
  tag_event_device_id: "match(^[a-zA-Z0-9]{32}$)"
  camera_rtsp_stream: "match(^rtsp:\/\/.*)"
